name: era5-nuts-binder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy>=1.12
  - matplotlib>=2.0
  - pandas>=0.22
  - scipy>=1.0
  - statsmodels
  - enlopy
  - netcdf4
  - xarray
  - ipywidgets
  - dask
  - rise
  - geopandas
